# Generated by Django 5.2.7 on 2025-10-21 17:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='conteudo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
